<?php
/**
 * Global configuration file for Cecil.
 *
 * Cecil, the de facto CMS for the Sleepy web application framework.
 * Copyright 2012 - 2014, Alex Palaistras (http://thoughtmonster.org)
 *
 * @copyright	Copyright 2012 - 2014, Alex Palaistras (http://thoughtmonster.org)
 * @link		http://thoughtmonster.org/cecil
 * @package		Cecil.Core
 * @since		Cecil 0.1.0
 */

/*
 * Client-related configuration options.
 *
 * 'path'			Path to client base directory (the one containing 'init.php').
 * 'authkey'		The key which the server is to authenticate against.
 * 'environment'	The runtime environment which the client will use to
 * 					determine error reporting etc. The presets are:
 *					'development' and 'production'.
 */

$config['client']['path']		 = '/srv/sleepy/';
$config['client']['authkey']	 = '';
$config['client']['environment'] = 'development';

/*
 * Template-related configuration options.
 *
 * 'type'			Template language/extension to use. 'Mustache' is the
 * 					only template language supported as of now.
 * 'lang'			The language used in our template source, which is the
 * 					basis for all other translations.
 */

$config['template']['type'] = 'mustache';
$config['template']['lang'] = 'en';

/* 
 * App-related configuration options.
 *
 * 	'lang'			The default display language for this application. Usually is
 * 					the same as the template language, though this is configurable
 * 					by users.
 */

$config['app']['lang'] = 'en';

/*
 * Database-related configuration options.
 *
 * 'default'		Default database name, containing users etc.
 * 'prefix'			Prefix used for our per-client autogenerated databases.
 *
 */

$config['database']['default']	= 'cecil';
$config['database']['prefix']	= 'cecil_';

/* End of file config.php */
